heater_mode:
  register: "0b55"
  decode: heater_mode
  encode: heater_mode

room_mode:
  register: "0b32"
  decode: raw_int
  encode: raw_int

cwu_mode:
  register: "0b30"
  decode: raw_int
  encode: raw_int

is_water_heater_enabled:
  register: "0b55"
  bit_index: 4
  decode:
    type: map
    true_value: WaterHeaterEnabled.ENABLED
    false_value: WaterHeaterEnabled.DISABLED
  encode:
    type: map
    true_value: WaterHeaterEnabled.ENABLED
    false_value: WaterHeaterEnabled.DISABLED

is_pump_co_running:
  register: "0b51"
  bit_index: 0
  decode:
    type: map
    true_value: PumpStatus.RUNNING
    false_value: PumpStatus.IDLE

is_pump_circulation_running:
  register: "0b51"
  bit_index: 1
  decode:
    type: map
    true_value: PumpStatus.RUNNING
    false_value: PumpStatus.IDLE

valve_position:
  register: "0b51"
  bit_index: 2
  decode:
    type: map
    true_value: ValvePosition.CO
    false_value: ValvePosition.DHW

manual_temperature:
  register: "0b8d"
  decode: scaled_x10
  encode: scaled_x10

room_temperature_economy:
  register: "0b68"
  decode: scaled_x10
  encode: scaled_x10

room_temperature_comfort:
  register: "0b6a"
  decode: scaled_x10
  encode: scaled_x10

room_temperature_comfort_plus:
  register: "0b6b"
  decode: scaled_x10
  encode: scaled_x10

room_temperature_comfort_minus:
  register: "0b69"
  decode: scaled_x10
  encode: scaled_x10

cwu_temperature_economy:
  register: "0b66"
  decode: scaled_x10
  encode: scaled_x10

cwu_temperature_comfort:
  register: "0b67"
  decode: scaled_x10
  encode: scaled_x10

pressure:
  register: "0b4e"
  decode: scaled_x100

water_current_temperature:
  register: "0b4a"
  decode: scaled_x10

inlet_temperature:
  register: "0b48"
  decode: scaled_x10

outlet_temperature:
  register: "0b49"
  decode: scaled_x10

outside_temperature:
  register: "0b4c"
  decode: scaled_x10

supply_setpoint:
  register: "0b2f"
  decode: scaled_x10

room_setpoint:
  register: "0b31"
  decode: scaled_x10

power:
  register: "0b46"
  decode: scaled_x10

flow:
  register: "0b4f"
  decode: scaled_x10

error_code:
  register: "0b52"
  decode: raw_int

work_mode:
  register: "0b8a"
  decode: raw_int

room_temperature:
  register: "0b4b"
  decode: scaled_x10

party_vacation_end_minute:
  register: "0b6c"
  decode: raw_int
  encode: raw_int

party_vacation_end_hour:
  register: "0b6d"
  decode: raw_int
  encode: raw_int

party_vacation_end_day:
  register: "0b6e"
  decode: raw_int
  encode: raw_int

party_vacation_end_month:
  register: "0b6f"
  decode: raw_int
  encode: raw_int

party_vacation_end_year:
  register: "0b70"
  decode: raw_int
  encode: raw_int
